### ISSUE TITLE
Lettuce CI enhancements

### ISSUE THREAD

**Issue by chayim** [lettuce-io/lettuce-core#2747]
- [ ] Initial support for CI as part of lettuce pull requests
- [ ] Trigger nightly runs of CI against main branch
- [ ] Enable code coverage via codecov for lettuce tests
- [ ] Integrate spellcheck support for documentation
- [ ] Snapshot builds should publish to mavenhub when merged to an actively supporting branch
- [ ] Ensure that releases can automatically publish to mavenhub
